
(dockerfile-mode . [(20181103 1826) ((emacs (24)) (s (1 12))) "Major mode for editing Docker's Dockerfiles" single ((:commit . "9c788e04e7f836af12652685b1ffa88ad0a40c98") (:url . "https://github.com/spotify/dockerfile-mode"))])
